/**
 * Report Catalog
 * 
 * Comprehensive catalog of 70+ standard reports organized by category.
 * Each report includes metadata for rendering, API queries, and exports.
 */

export interface ReportDefinition {
  id: string;
  name: string;
  category: ReportCategory;
  description: string;
  dimensions: string[];
  measures: string[];
  filters?: FilterDefinition[];
  defaultDateRange: 'today' | 'yesterday' | 'last7days' | 'last30days' | 'mtd' | 'ytd';
  refreshInterval?: number; // seconds
  visualization: VisualizationType[];
  exportFormats: ExportFormat[];
  accessLevel: AccessLevel;
  tags: string[];
}

export type ReportCategory = 
  | 'sales_revenue'
  | 'operational'
  | 'ancillary'
  | 'financial'
  | 'customer'
  | 'marketing'
  | 'executive';

export type VisualizationType = 
  | 'table'
  | 'line_chart'
  | 'bar_chart'
  | 'pie_chart'
  | 'area_chart'
  | 'scatter_chart'
  | 'heatmap'
  | 'gauge'
  | 'kpi_card';

export type ExportFormat = 'pdf' | 'excel' | 'csv' | 'json' | 'powerpoint';

export type AccessLevel = 'public' | 'analyst' | 'manager' | 'executive' | 'admin';

export interface FilterDefinition {
  field: string;
  type: 'select' | 'multiselect' | 'date_range' | 'number_range' | 'text';
  required: boolean;
  defaultValue?: any;
}

/**
 * Complete Report Catalog (70+ reports)
 */
export const REPORT_CATALOG: ReportDefinition[] = [
  // ========================================================================
  // SALES & REVENUE REPORTS (15 reports)
  // ========================================================================
  {
    id: 'daily-booking-summary',
    name: 'Daily Booking Summary',
    category: 'sales_revenue',
    description: 'Daily overview of bookings, passengers, and revenue by channel',
    dimensions: ['date', 'channel', 'route'],
    measures: ['bookingCount', 'passengerCount', 'totalRevenue', 'avgBookingValue'],
    defaultDateRange: 'last30days',
    refreshInterval: 300,
    visualization: ['table', 'line_chart', 'bar_chart'],
    exportFormats: ['pdf', 'excel', 'csv'],
    accessLevel: 'analyst',
    tags: ['daily', 'bookings', 'revenue', 'popular'],
  },
  {
    id: 'revenue-by-route',
    name: 'Revenue by Route and Market',
    category: 'sales_revenue',
    description: 'Revenue analysis by route with market segmentation',
    dimensions: ['route', 'market_type', 'cabin_class'],
    measures: ['ticketRevenue', 'ancillaryRevenue', 'totalRevenue', 'passengerCount', 'loadFactor'],
    defaultDateRange: 'mtd',
    visualization: ['table', 'bar_chart', 'heatmap'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['revenue', 'routes', 'markets'],
  },
  {
    id: 'channel-performance',
    name: 'Channel Performance Comparison',
    category: 'sales_revenue',
    description: 'Booking and revenue comparison across distribution channels',
    dimensions: ['channel', 'date'],
    measures: ['bookingCount', 'totalRevenue', 'conversionRate', 'distributionCost', 'netRevenue'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'pie_chart', 'table'],
    exportFormats: ['pdf', 'excel', 'powerpoint'],
    accessLevel: 'manager',
    tags: ['channels', 'performance', 'distribution'],
  },
  {
    id: 'conversion-funnel',
    name: 'Conversion Funnel Analysis',
    category: 'sales_revenue',
    description: 'Step-by-step analysis of booking conversion from search to purchase',
    dimensions: ['channel', 'date', 'device_type'],
    measures: ['searchCount', 'flightSelectCount', 'passengerInfoCount', 'paymentCount', 'bookingCount', 'conversionRate'],
    defaultDateRange: 'last7days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['conversion', 'funnel', 'optimization'],
  },
  {
    id: 'booking-pace',
    name: 'Booking Pace vs. Forecast',
    category: 'sales_revenue',
    description: 'Actual bookings compared to forecast by departure date',
    dimensions: ['departure_date', 'route', 'cabin_class'],
    measures: ['actualBookings', 'forecastBookings', 'variance', 'variancePercent'],
    defaultDateRange: 'last30days',
    visualization: ['line_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['forecast', 'pace', 'revenue_management'],
  },
  {
    id: 'fare-mix-analysis',
    name: 'Fare Mix Analysis',
    category: 'sales_revenue',
    description: 'Distribution of bookings across fare families',
    dimensions: ['fare_family', 'route', 'cabin_class'],
    measures: ['bookingCount', 'passengerCount', 'avgFare', 'totalRevenue', 'marketShare'],
    defaultDateRange: 'mtd',
    visualization: ['pie_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['fares', 'pricing', 'mix'],
  },
  {
    id: 'group-bookings',
    name: 'Group Bookings Report',
    category: 'sales_revenue',
    description: 'Analysis of group bookings (10+ passengers)',
    dimensions: ['booking_date', 'departure_date', 'route'],
    measures: ['groupCount', 'totalPassengers', 'avgGroupSize', 'totalRevenue', 'avgRevenuePerGroup'],
    filters: [
      { field: 'min_group_size', type: 'number_range', required: false, defaultValue: 10 },
    ],
    defaultDateRange: 'last30days',
    visualization: ['table', 'bar_chart'],
    exportFormats: ['excel', 'csv'],
    accessLevel: 'analyst',
    tags: ['groups', 'large_bookings'],
  },
  {
    id: 'agent-productivity',
    name: 'Agent Productivity Report',
    category: 'sales_revenue',
    description: 'Booking performance metrics by sales agent',
    dimensions: ['agent_name', 'agency', 'date'],
    measures: ['bookingCount', 'passengerCount', 'totalRevenue', 'commission', 'avgBookingValue', 'productivity_rank'],
    defaultDateRange: 'mtd',
    visualization: ['table', 'bar_chart'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['agents', 'productivity', 'sales'],
  },
  {
    id: 'advance-purchase',
    name: 'Advance Purchase Analysis',
    category: 'sales_revenue',
    description: 'Booking distribution by days before departure',
    dimensions: ['advance_purchase_bucket', 'route', 'cabin_class'],
    measures: ['bookingCount', 'avgFare', 'totalRevenue'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['advance_purchase', 'booking_behavior'],
  },
  {
    id: 'revenue-variance',
    name: 'Revenue Variance Analysis',
    category: 'sales_revenue',
    description: 'Actual vs budget revenue with variance analysis',
    dimensions: ['month', 'route', 'cabin_class'],
    measures: ['actualRevenue', 'budgetRevenue', 'variance', 'variancePercent'],
    defaultDateRange: 'ytd',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel', 'powerpoint'],
    accessLevel: 'executive',
    tags: ['budget', 'variance', 'executive'],
  },
  
  // Additional Sales & Revenue Reports
  {
    id: 'market-share',
    name: 'Market Share by Route',
    category: 'sales_revenue',
    description: 'Market share analysis compared to competitors',
    dimensions: ['route', 'month'],
    measures: ['ourBookings', 'totalMarketBookings', 'marketShare', 'rankPosition'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'executive',
    tags: ['market_share', 'competition'],
  },
  {
    id: 'pricing-elasticity',
    name: 'Price Elasticity Analysis',
    category: 'sales_revenue',
    description: 'Demand response to price changes',
    dimensions: ['route', 'price_bucket'],
    measures: ['avgPrice', 'bookingCount', 'elasticity', 'revenueImpact'],
    defaultDateRange: 'last30days',
    visualization: ['scatter_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['pricing', 'elasticity', 'revenue_management'],
  },
  {
    id: 'corporate-accounts',
    name: 'Corporate Account Performance',
    category: 'sales_revenue',
    description: 'Revenue and volume from corporate accounts',
    dimensions: ['corporate_account', 'month'],
    measures: ['bookingCount', 'passengerCount', 'totalRevenue', 'discount', 'netRevenue'],
    defaultDateRange: 'ytd',
    visualization: ['table', 'bar_chart'],
    exportFormats: ['excel', 'pdf'],
    accessLevel: 'manager',
    tags: ['corporate', 'accounts'],
  },
  {
    id: 'cancellation-analysis',
    name: 'Cancellation Analysis',
    category: 'sales_revenue',
    description: 'Booking cancellations by reason and timing',
    dimensions: ['cancellation_reason', 'days_before_departure', 'route'],
    measures: ['cancelledBookings', 'refundAmount', 'cancellationFee', 'netImpact'],
    defaultDateRange: 'last30days',
    visualization: ['pie_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['cancellations', 'refunds'],
  },
  {
    id: 'weekend-vs-weekday',
    name: 'Weekend vs Weekday Performance',
    category: 'sales_revenue',
    description: 'Booking and revenue comparison for weekends vs weekdays',
    dimensions: ['day_type', 'route', 'hour_of_day'],
    measures: ['bookingCount', 'totalRevenue', 'avgBookingValue'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['day_of_week', 'patterns'],
  },
  
  // ========================================================================
  // OPERATIONAL REPORTS (15 reports)
  // ========================================================================
  {
    id: 'on-time-performance',
    name: 'On-Time Performance',
    category: 'operational',
    description: 'Flight punctuality metrics by route and time period',
    dimensions: ['route', 'date', 'flight_number'],
    measures: ['totalFlights', 'onTimeFlights', 'delayedFlights', 'otpPercent', 'avgDelayMinutes'],
    defaultDateRange: 'last30days',
    refreshInterval: 600,
    visualization: ['bar_chart', 'line_chart', 'gauge', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['otp', 'delays', 'punctuality', 'popular'],
  },
  {
    id: 'delay-analysis',
    name: 'Delay Analysis by Cause',
    category: 'operational',
    description: 'Breakdown of flight delays by root cause',
    dimensions: ['delay_code', 'delay_category', 'route'],
    measures: ['delayCount', 'totalDelayMinutes', 'avgDelayMinutes', 'flights_affected'],
    defaultDateRange: 'last30days',
    visualization: ['pie_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['delays', 'causes', 'analysis'],
  },
  {
    id: 'turnaround-time',
    name: 'Turnaround Time Analysis',
    category: 'operational',
    description: 'Aircraft turnaround time by station and aircraft type',
    dimensions: ['station', 'aircraft_type', 'date'],
    measures: ['avgTurnaroundTime', 'minTurnaroundTime', 'maxTurnaroundTime', 'targetTurnaroundTime', 'compliancePercent'],
    defaultDateRange: 'last7days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['turnaround', 'ground_ops'],
  },
  {
    id: 'baggage-handling',
    name: 'Baggage Handling Metrics',
    category: 'operational',
    description: 'Baggage mishandling, delayed, and lost bags analysis',
    dimensions: ['station', 'route', 'date'],
    measures: ['totalBags', 'delayedBags', 'lostBags', 'damagedBags', 'mishandlingRate', 'resolutionTime'],
    defaultDateRange: 'last30days',
    visualization: ['line_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['baggage', 'mishandling'],
  },
  {
    id: 'checkin-efficiency',
    name: 'Check-In Efficiency',
    category: 'operational',
    description: 'Check-in channel usage and processing times',
    dimensions: ['checkin_channel', 'station', 'date'],
    measures: ['checkinCount', 'avgProcessingTime', 'webCheckinPercent', 'mobileCheckinPercent', 'kioskCheckinPercent'],
    defaultDateRange: 'last7days',
    visualization: ['pie_chart', 'bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['checkin', 'efficiency', 'channels'],
  },
  {
    id: 'boarding-speed',
    name: 'Boarding Speed Metrics',
    category: 'operational',
    description: 'Gate boarding speed and zone compliance',
    dimensions: ['station', 'gate', 'aircraft_type'],
    measures: ['avgBoardingTime', 'targetBoardingTime', 'passengersPerMinute', 'zoneCompliance', 'delayedBoardings'],
    defaultDateRange: 'last7days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['boarding', 'gates', 'speed'],
  },
  {
    id: 'load-factor',
    name: 'Load Factor by Flight',
    category: 'operational',
    description: 'Seat utilization and load factor metrics',
    dimensions: ['route', 'flight_number', 'date', 'cabin_class'],
    measures: ['totalSeats', 'bookedSeats', 'loadFactor', 'revenuePerSeat', 'yieldPerPassenger'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'heatmap', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['load_factor', 'capacity', 'utilization'],
  },
  {
    id: 'no-show-analysis',
    name: 'No-Show Analysis',
    category: 'operational',
    description: 'Passenger no-show patterns and impact',
    dimensions: ['route', 'cabin_class', 'fare_family'],
    measures: ['bookedPassengers', 'noShowCount', 'noShowRate', 'revenueImpact'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['no_show', 'revenue_impact'],
  },
  
  // Additional Operational Reports
  {
    id: 'aircraft-utilization',
    name: 'Aircraft Utilization',
    category: 'operational',
    description: 'Aircraft utilization hours and cycles',
    dimensions: ['aircraft_registration', 'aircraft_type', 'month'],
    measures: ['flightHours', 'blockHours', 'cycles', 'utilizationPercent', 'targetUtilization'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['excel', 'pdf'],
    accessLevel: 'manager',
    tags: ['aircraft', 'utilization'],
  },
  {
    id: 'crew-productivity',
    name: 'Crew Productivity',
    category: 'operational',
    description: 'Flight crew and cabin crew productivity metrics',
    dimensions: ['base_station', 'crew_type', 'month'],
    measures: ['flightHours', 'dutyHours', 'restDays', 'overtimeHours', 'productivity_ratio'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['crew', 'productivity'],
  },
  {
    id: 'fuel-consumption',
    name: 'Fuel Consumption Analysis',
    category: 'operational',
    description: 'Fuel usage by route and aircraft type',
    dimensions: ['route', 'aircraft_type', 'month'],
    measures: ['totalFuel', 'avgFuelPerFlight', 'fuelCost', 'fuelEfficiency'],
    defaultDateRange: 'last30days',
    visualization: ['line_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['fuel', 'cost', 'efficiency'],
  },
  {
    id: 'maintenance-downtime',
    name: 'Maintenance Downtime',
    category: 'operational',
    description: 'Aircraft out of service for maintenance',
    dimensions: ['aircraft_type', 'maintenance_type', 'month'],
    measures: ['downtimeHours', 'scheduledDowntime', 'unscheduledDowntime', 'impactedFlights'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['maintenance', 'downtime'],
  },
  {
    id: 'safety-incidents',
    name: 'Safety Incidents Report',
    category: 'operational',
    description: 'Safety incident tracking and categorization',
    dimensions: ['incident_category', 'severity', 'station'],
    measures: ['incidentCount', 'closedIncidents', 'openIncidents', 'avgResolutionDays'],
    defaultDateRange: 'last30days',
    visualization: ['pie_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'executive',
    tags: ['safety', 'incidents', 'compliance'],
  },
  {
    id: 'weight-balance-summary',
    name: 'Weight & Balance Summary',
    category: 'operational',
    description: 'Load control compliance and CG positioning',
    dimensions: ['route', 'aircraft_type', 'date'],
    measures: ['avgLoadFactor', 'avgCG', 'cgViolations', 'weightViolations', 'optimizationOpportunities'],
    defaultDateRange: 'last7days',
    visualization: ['line_chart', 'scatter_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['load_control', 'weight_balance'],
  },
  {
    id: 'customer-service-metrics',
    name: 'Customer Service Metrics',
    category: 'operational',
    description: 'Customer service performance and satisfaction',
    dimensions: ['service_type', 'station', 'date'],
    measures: ['requestCount', 'avgHandlingTime', 'resolutionRate', 'satisfactionScore'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'gauge', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['customer_service', 'satisfaction'],
  },
  
  // ========================================================================
  // ANCILLARY REPORTS (12 reports)
  // ========================================================================
  {
    id: 'ancillary-revenue',
    name: 'Ancillary Revenue by Product',
    category: 'ancillary',
    description: 'Revenue breakdown by ancillary product category',
    dimensions: ['product_category', 'product_name', 'date'],
    measures: ['quantity', 'totalRevenue', 'avgPrice', 'margin', 'netRevenue'],
    defaultDateRange: 'mtd',
    visualization: ['pie_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['ancillary', 'revenue', 'products'],
  },
  {
    id: 'attach-rate',
    name: 'Attach Rate by Route',
    category: 'ancillary',
    description: 'Ancillary purchase rate by route and product',
    dimensions: ['route', 'product_category'],
    measures: ['totalBookings', 'bookingsWithProduct', 'attachRate', 'revenuePerBooking'],
    defaultDateRange: 'last30days',
    visualization: ['heatmap', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['attach_rate', 'ancillary', 'routes'],
  },
  {
    id: 'bundle-performance',
    name: 'Bundle Performance',
    category: 'ancillary',
    description: 'Performance of product bundles vs individual sales',
    dimensions: ['bundle_name', 'route'],
    measures: ['bundleSales', 'bundleRevenue', 'individualSales', 'bundleUplift', 'avgBundleValue'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['bundles', 'packages'],
  },
  {
    id: 'seat-selection',
    name: 'Seat Selection Analysis',
    category: 'ancillary',
    description: 'Paid seat selection revenue and preferences',
    dimensions: ['seat_type', 'route', 'cabin_class'],
    measures: ['seatsSold', 'revenue', 'avgPrice', 'selectionRate'],
    defaultDateRange: 'last30days',
    visualization: ['pie_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['seats', 'selection', 'ancillary'],
  },
  {
    id: 'baggage-revenue',
    name: 'Baggage Revenue Analysis',
    category: 'ancillary',
    description: 'Paid baggage revenue by weight and route',
    dimensions: ['baggage_type', 'route'],
    measures: ['bagsSold', 'totalWeight', 'revenue', 'avgRevenuePerBag'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['baggage', 'revenue'],
  },
  {
    id: 'merchandising-effectiveness',
    name: 'Merchandising Effectiveness',
    category: 'ancillary',
    description: 'Effectiveness of ancillary merchandising campaigns',
    dimensions: ['campaign_name', 'product_category', 'channel'],
    measures: ['impressions', 'clicks', 'conversions', 'revenue', 'roi'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['merchandising', 'campaigns', 'marketing'],
  },
  {
    id: 'upsell-conversion',
    name: 'Upsell Conversion Rates',
    category: 'ancillary',
    description: 'Conversion rates for upsell offers',
    dimensions: ['upsell_type', 'channel', 'customer_segment'],
    measures: ['offersShown', 'offersAccepted', 'conversionRate', 'revenue', 'avgUpsellValue'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'analyst',
    tags: ['upsell', 'conversion', 'offers'],
  },
  
  // Additional Ancillary Reports
  {
    id: 'lounge-access',
    name: 'Lounge Access Revenue',
    category: 'ancillary',
    description: 'Lounge access sales and usage',
    dimensions: ['lounge_location', 'access_type'],
    measures: ['passesSold', 'revenue', 'avgPrice', 'capacity_utilization'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'analyst',
    tags: ['lounge', 'access'],
  },
  {
    id: 'wifi-usage',
    name: 'In-Flight WiFi Revenue',
    category: 'ancillary',
    description: 'WiFi purchase and usage patterns',
    dimensions: ['route', 'aircraft_type'],
    measures: ['passesSold', 'revenue', 'dataUsage', 'avgSessionDuration'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'analyst',
    tags: ['wifi', 'connectivity'],
  },
  {
    id: 'priority-boarding',
    name: 'Priority Boarding Revenue',
    category: 'ancillary',
    description: 'Priority boarding sales analysis',
    dimensions: ['route', 'cabin_class'],
    measures: ['priorityPassengers', 'revenue', 'attachRate'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'analyst',
    tags: ['priority', 'boarding'],
  },
  {
    id: 'insurance-sales',
    name: 'Travel Insurance Sales',
    category: 'ancillary',
    description: 'Trip protection insurance performance',
    dimensions: ['insurance_type', 'route_type'],
    measures: ['policiesSold', 'revenue', 'attachRate', 'claimRate'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'pie_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'analyst',
    tags: ['insurance', 'protection'],
  },
  {
    id: 'ancillary-channel-mix',
    name: 'Ancillary Channel Mix',
    category: 'ancillary',
    description: 'Ancillary sales by purchase timing and channel',
    dimensions: ['purchase_timing', 'channel', 'product_category'],
    measures: ['revenue', 'quantity', 'avgPrice'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'pie_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'analyst',
    tags: ['channel', 'timing'],
  },
  
  // ========================================================================
  // FINANCIAL REPORTS (13 reports)
  // ========================================================================
  {
    id: 'revenue-recognition',
    name: 'Revenue Recognition',
    category: 'financial',
    description: 'Earned vs unearned revenue tracking',
    dimensions: ['month', 'route', 'cabin_class'],
    measures: ['totalRevenue', 'earnedRevenue', 'unearnedRevenue', 'recognitionPercent'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['revenue', 'accounting'],
  },
  {
    id: 'payment-reconciliation',
    name: 'Payment Reconciliation',
    category: 'financial',
    description: 'Payment gateway reconciliation and settlement',
    dimensions: ['payment_method', 'gateway', 'date'],
    measures: ['transactionCount', 'grossAmount', 'fees', 'chargebacks', 'netAmount', 'settlementAmount'],
    defaultDateRange: 'yesterday',
    visualization: ['table', 'bar_chart'],
    exportFormats: ['excel', 'csv'],
    accessLevel: 'manager',
    tags: ['payments', 'reconciliation', 'finance'],
  },
  {
    id: 'refund-summary',
    name: 'Refund Summary',
    category: 'financial',
    description: 'Refund processing and impact analysis',
    dimensions: ['refund_reason', 'fare_family', 'date'],
    measures: ['refundCount', 'refundAmount', 'processingFee', 'netRefund', 'processingTime'],
    defaultDateRange: 'mtd',
    visualization: ['pie_chart', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['refunds', 'processing'],
  },
  {
    id: 'commission-tracking',
    name: 'Commission Tracking',
    category: 'financial',
    description: 'Agent commission calculation and payment tracking',
    dimensions: ['agent', 'agency', 'month'],
    measures: ['bookingRevenue', 'commissionRate', 'commissionAmount', 'paymentStatus'],
    defaultDateRange: 'mtd',
    visualization: ['table', 'bar_chart'],
    exportFormats: ['excel', 'csv'],
    accessLevel: 'manager',
    tags: ['commission', 'agents', 'payments'],
  },
  {
    id: 'bsp-arc-settlement',
    name: 'BSP/ARC Settlement',
    category: 'financial',
    description: 'BSP and ARC settlement reporting',
    dimensions: ['settlement_period', 'agency', 'country'],
    measures: ['grossSales', 'commissions', 'taxes', 'netRemittance'],
    defaultDateRange: 'last7days',
    visualization: ['table', 'bar_chart'],
    exportFormats: ['excel', 'csv'],
    accessLevel: 'manager',
    tags: ['bsp', 'arc', 'settlement'],
  },
  {
    id: 'receivables-aging',
    name: 'Receivables Aging',
    category: 'financial',
    description: 'Accounts receivable aging analysis',
    dimensions: ['customer_type', 'aging_bucket'],
    measures: ['outstandingAmount', 'current', 'days_30', 'days_60', 'days_90', 'days_90_plus'],
    defaultDateRange: 'today',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['excel', 'pdf'],
    accessLevel: 'manager',
    tags: ['receivables', 'aging', 'finance'],
  },
  
  // Additional Financial Reports
  {
    id: 'cost-per-seat',
    name: 'Cost Per Available Seat',
    category: 'financial',
    description: 'CASK (Cost per Available Seat Kilometer) analysis',
    dimensions: ['route', 'aircraft_type', 'month'],
    measures: ['totalCosts', 'availableSeatKm', 'cask', 'revenuePerSeat', 'profitMargin'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'executive',
    tags: ['costs', 'cask', 'profitability'],
  },
  {
    id: 'yield-management',
    name: 'Yield Management Report',
    category: 'financial',
    description: 'Revenue per passenger kilometer and yield analysis',
    dimensions: ['route', 'cabin_class', 'month'],
    measures: ['passengerKm', 'revenue', 'yield', 'loadFactor', 'revenuePerSeat'],
    defaultDateRange: 'mtd',
    visualization: ['line_chart', 'bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['yield', 'revenue_management'],
  },
  {
    id: 'tax-collection',
    name: 'Tax Collection Report',
    category: 'financial',
    description: 'Tax collection by type and jurisdiction',
    dimensions: ['tax_type', 'country', 'month'],
    measures: ['taxCollected', 'taxRemitted', 'taxPending', 'variance'],
    defaultDateRange: 'mtd',
    visualization: ['table', 'bar_chart'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['taxes', 'compliance'],
  },
  {
    id: 'currency-exposure',
    name: 'Currency Exposure Report',
    category: 'financial',
    description: 'Foreign exchange exposure and hedging',
    dimensions: ['currency', 'month'],
    measures: ['revenueInCurrency', 'exchangeRate', 'usdEquivalent', 'hedgedAmount', 'exposure'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['forex', 'currency', 'hedging'],
  },
  {
    id: 'proration-report',
    name: 'Interline Proration',
    category: 'financial',
    description: 'Interline revenue proration and settlement',
    dimensions: ['partner_airline', 'route', 'month'],
    measures: ['totalRevenue', 'ourShare', 'partnerShare', 'prorationPercent'],
    defaultDateRange: 'mtd',
    visualization: ['table', 'bar_chart'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['interline', 'proration'],
  },
  {
    id: 'cashflow-forecast',
    name: 'Cash Flow Forecast',
    category: 'financial',
    description: 'Short-term cash flow projection',
    dimensions: ['week', 'category'],
    measures: ['forecastInflow', 'forecastOutflow', 'netCashflow', 'cumulativeCash'],
    defaultDateRange: 'last7days',
    visualization: ['line_chart', 'bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'executive',
    tags: ['cashflow', 'forecast', 'treasury'],
  },
  {
    id: 'profitability-route',
    name: 'Route Profitability',
    category: 'financial',
    description: 'Profit and loss by route',
    dimensions: ['route', 'month'],
    measures: ['revenue', 'directCosts', 'allocatedCosts', 'grossProfit', 'netProfit', 'profitMargin'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['excel', 'pdf'],
    accessLevel: 'executive',
    tags: ['profitability', 'routes', 'p&l'],
  },
  
  // ========================================================================
  // CUSTOMER REPORTS (8 reports)
  // ========================================================================
  {
    id: 'customer-lifetime-value',
    name: 'Customer Lifetime Value',
    category: 'customer',
    description: 'CLV analysis by customer segment',
    dimensions: ['customer_segment', 'acquisition_channel'],
    measures: ['customerCount', 'avgLifetimeValue', 'avgBookings', 'avgRevenue', 'churnRate'],
    defaultDateRange: 'ytd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['clv', 'customer', 'value'],
  },
  {
    id: 'rfm-segmentation',
    name: 'RFM Segmentation Analysis',
    category: 'customer',
    description: 'Customer segmentation by recency, frequency, monetary',
    dimensions: ['rfm_segment'],
    measures: ['customerCount', 'avgRecencyDays', 'avgFrequency', 'avgMonetaryValue', 'totalRevenue'],
    defaultDateRange: 'last30days',
    visualization: ['pie_chart', 'bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['rfm', 'segmentation', 'customer'],
  },
  {
    id: 'frequent-flyer',
    name: 'Frequent Flyer Program Report',
    category: 'customer',
    description: 'Loyalty program membership and activity',
    dimensions: ['tier', 'month'],
    measures: ['members', 'newMembers', 'upgrades', 'downgrades', 'activeMembers', 'avgFlights'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['loyalty', 'frequent_flyer'],
  },
  {
    id: 'churn-analysis',
    name: 'Customer Churn Analysis',
    category: 'customer',
    description: 'Customer churn prediction and at-risk segments',
    dimensions: ['customer_segment', 'churn_risk'],
    measures: ['customersAtRisk', 'churnRate', 'revenueAtRisk', 'avgDaysSinceLastBooking'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'pie_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['churn', 'retention', 'risk'],
  },
  {
    id: 'customer-satisfaction',
    name: 'Customer Satisfaction Metrics',
    category: 'customer',
    description: 'NPS, CSAT, and satisfaction scores',
    dimensions: ['touchpoint', 'route', 'date'],
    measures: ['surveyCount', 'nps', 'csat', 'promoters', 'passives', 'detractors'],
    defaultDateRange: 'last30days',
    visualization: ['gauge', 'bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'excel'],
    accessLevel: 'manager',
    tags: ['satisfaction', 'nps', 'csat'],
  },
  {
    id: 'customer-complaints',
    name: 'Customer Complaints Analysis',
    category: 'customer',
    description: 'Complaint categorization and resolution',
    dimensions: ['complaint_category', 'severity', 'route'],
    measures: ['complaintCount', 'resolvedComplaints', 'avgResolutionDays', 'compensationPaid'],
    defaultDateRange: 'last30days',
    visualization: ['pie_chart', 'bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['complaints', 'resolution'],
  },
  {
    id: 'booking-patterns',
    name: 'Customer Booking Patterns',
    category: 'customer',
    description: 'Behavioral patterns and preferences',
    dimensions: ['customer_segment', 'route_type'],
    measures: ['avgAdvancePurchase', 'preferredCabin', 'preferredChannel', 'avgBookingValue', 'repeatRate'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'heatmap', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'analyst',
    tags: ['patterns', 'behavior'],
  },
  {
    id: 'customer-acquisition-cost',
    name: 'Customer Acquisition Cost',
    category: 'customer',
    description: 'CAC by acquisition channel',
    dimensions: ['acquisition_channel', 'month'],
    measures: ['newCustomers', 'marketingSpend', 'cac', 'ltv', 'ltv_cac_ratio'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['acquisition', 'cac', 'marketing'],
  },
  
  // ========================================================================
  // MARKETING REPORTS (5 reports)
  // ========================================================================
  {
    id: 'campaign-performance',
    name: 'Marketing Campaign Performance',
    category: 'marketing',
    description: 'Campaign effectiveness and ROI',
    dimensions: ['campaign_name', 'channel', 'customer_segment'],
    measures: ['spend', 'impressions', 'clicks', 'conversions', 'revenue', 'roi', 'cpa'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['pdf', 'excel', 'powerpoint'],
    accessLevel: 'manager',
    tags: ['campaigns', 'marketing', 'roi'],
  },
  {
    id: 'email-marketing',
    name: 'Email Marketing Performance',
    category: 'marketing',
    description: 'Email campaign metrics',
    dimensions: ['email_campaign', 'customer_segment'],
    measures: ['sentCount', 'openRate', 'clickRate', 'conversionRate', 'unsubscribeRate', 'revenue'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'analyst',
    tags: ['email', 'marketing'],
  },
  {
    id: 'social-media',
    name: 'Social Media Engagement',
    category: 'marketing',
    description: 'Social media metrics and engagement',
    dimensions: ['platform', 'content_type', 'date'],
    measures: ['posts', 'impressions', 'engagements', 'likes', 'shares', 'comments', 'engagementRate'],
    defaultDateRange: 'last30days',
    visualization: ['line_chart', 'bar_chart', 'table'],
    exportFormats: ['excel', 'powerpoint'],
    accessLevel: 'analyst',
    tags: ['social_media', 'engagement'],
  },
  {
    id: 'seo-performance',
    name: 'SEO Performance',
    category: 'marketing',
    description: 'Search engine optimization metrics',
    dimensions: ['keyword', 'landing_page', 'month'],
    measures: ['impressions', 'clicks', 'averagePosition', 'ctr', 'conversions'],
    defaultDateRange: 'last30days',
    visualization: ['line_chart', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'analyst',
    tags: ['seo', 'search', 'organic'],
  },
  {
    id: 'attribution-analysis',
    name: 'Multi-Touch Attribution',
    category: 'marketing',
    description: 'Marketing attribution modeling',
    dimensions: ['touchpoint', 'position', 'channel'],
    measures: ['attributedConversions', 'attributedRevenue', 'contributionPercent'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'heatmap', 'table'],
    exportFormats: ['excel'],
    accessLevel: 'manager',
    tags: ['attribution', 'touchpoints'],
  },
  
  // ========================================================================
  // EXECUTIVE REPORTS (7 reports)
  // ========================================================================
  {
    id: 'executive-dashboard',
    name: 'Executive Summary Dashboard',
    category: 'executive',
    description: 'High-level KPIs and performance metrics',
    dimensions: ['date'],
    measures: ['totalRevenue', 'loadFactor', 'onTimePerformance', 'netProfit', 'customerSatisfaction', 'marketShare'],
    defaultDateRange: 'mtd',
    refreshInterval: 300,
    visualization: ['kpi_card', 'line_chart', 'gauge'],
    exportFormats: ['pdf', 'powerpoint'],
    accessLevel: 'executive',
    tags: ['executive', 'kpis', 'dashboard', 'popular'],
  },
  {
    id: 'monthly-performance',
    name: 'Monthly Performance Report',
    category: 'executive',
    description: 'Comprehensive monthly business review',
    dimensions: ['month'],
    measures: ['revenue', 'passengers', 'loadFactor', 'yield', 'cask', 'profit', 'cash'],
    defaultDateRange: 'mtd',
    visualization: ['bar_chart', 'line_chart', 'table'],
    exportFormats: ['pdf', 'powerpoint'],
    accessLevel: 'executive',
    tags: ['monthly', 'executive', 'comprehensive'],
  },
  {
    id: 'quarterly-business-review',
    name: 'Quarterly Business Review',
    category: 'executive',
    description: 'Quarterly strategic performance review',
    dimensions: ['quarter', 'business_unit'],
    measures: ['revenue', 'profit', 'marketShare', 'customerGrowth', 'efficiency'],
    defaultDateRange: 'ytd',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['pdf', 'powerpoint'],
    accessLevel: 'executive',
    tags: ['quarterly', 'qbr', 'executive'],
  },
  {
    id: 'board-report',
    name: 'Board of Directors Report',
    category: 'executive',
    description: 'Summary report for board meetings',
    dimensions: ['month'],
    measures: ['revenue', 'ebitda', 'netIncome', 'loadFactor', 'yield', 'cashPosition', 'debt'],
    defaultDateRange: 'ytd',
    visualization: ['kpi_card', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'powerpoint'],
    accessLevel: 'executive',
    tags: ['board', 'executive', 'governance'],
  },
  {
    id: 'network-performance',
    name: 'Network Performance Summary',
    category: 'executive',
    description: 'Route network performance overview',
    dimensions: ['region', 'market_type'],
    measures: ['revenue', 'passengers', 'loadFactor', 'profitability', 'marketShare'],
    defaultDateRange: 'mtd',
    visualization: ['heatmap', 'bar_chart', 'table'],
    exportFormats: ['pdf', 'powerpoint'],
    accessLevel: 'executive',
    tags: ['network', 'routes', 'executive'],
  },
  {
    id: 'competitive-analysis',
    name: 'Competitive Analysis',
    category: 'executive',
    description: 'Competitive positioning and market share',
    dimensions: ['competitor', 'route', 'metric'],
    measures: ['ourPerformance', 'competitorPerformance', 'delta', 'rank'],
    defaultDateRange: 'last30days',
    visualization: ['bar_chart', 'table'],
    exportFormats: ['pdf', 'powerpoint'],
    accessLevel: 'executive',
    tags: ['competition', 'market_share'],
  },
  {
    id: 'risk-dashboard',
    name: 'Risk Dashboard',
    category: 'executive',
    description: 'Enterprise risk monitoring',
    dimensions: ['risk_category', 'severity'],
    measures: ['openRisks', 'mitigatedRisks', 'riskScore', 'financialImpact'],
    defaultDateRange: 'today',
    visualization: ['gauge', 'pie_chart', 'table'],
    exportFormats: ['pdf'],
    accessLevel: 'executive',
    tags: ['risk', 'compliance', 'executive'],
  },
];

/**
 * Get report by ID
 */
export function getReportById(id: string): ReportDefinition | undefined {
  return REPORT_CATALOG.find(r => r.id === id);
}

/**
 * Get reports by category
 */
export function getReportsByCategory(category: ReportCategory): ReportDefinition[] {
  return REPORT_CATALOG.filter(r => r.category === category);
}

/**
 * Get reports by access level
 */
export function getReportsByAccessLevel(level: AccessLevel): ReportDefinition[] {
  const accessHierarchy: Record<AccessLevel, number> = {
    public: 0,
    analyst: 1,
    manager: 2,
    executive: 3,
    admin: 4,
  };
  
  return REPORT_CATALOG.filter(r => accessHierarchy[r.accessLevel] <= accessHierarchy[level]);
}

/**
 * Search reports
 */
export function searchReports(query: string): ReportDefinition[] {
  const lowerQuery = query.toLowerCase();
  return REPORT_CATALOG.filter(r =>
    r.name.toLowerCase().includes(lowerQuery) ||
    r.description.toLowerCase().includes(lowerQuery) ||
    r.tags.some(tag => tag.includes(lowerQuery))
  );
}
